# Q.1
아래 출력값을 갖도록 a 변수값을 설정 (Hint: np.arange(n) 활용)

In [ ]:
#a = ??
import torch
import numpy as np

a = np.arange(24).reshape(2,3,4)

print("Shape :", a.shape)
print("Value :", a)

Shape : (2, 3, 4)
Value : [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



#Output
Shape : (2,3,4)
- Value : [[[ 0 1 2 3]
- [ 4 5 6 7]
- [8 9 10 11]

- [[12 13 14 15]
- [16 17 18 19]
*이탤릭체 텍스트*- [20 21 22 23]]]

# Q.2
Exercise 1의 a값과 slicing을 통해, 다음 두 값을 출력

In [ ]:
#print(a[???]) #Problem1
#print(a[???]) #Problem2

print(a[0,1:3,2:4]) #Problem1
print(np.reshape(a[0,1:3,2:4], (1,2,2))) #Problem2

[[ 6  7]
 [10 11]]
[[[ 6  7]
  [10 11]]]


# Q.3
test.csv 데이터를 활용하여, 70, 80, 90에 대한 Total Score 구하기 (nn.Module 활용) *Hint: numpy genfromtext 활용

In [ ]:
data = open('test.csv', 'r')
print(data)

<_io.TextIOWrapper name='test.csv' mode='r' encoding='UTF-8'>


In [ ]:
import csv

with open('test.csv' , 'r') as f :
    dat = [k for k in csv.reader(f)]
print(dat)

[['73', '80', '75', '152'], ['93', '88', '93', '185'], ['89', '91', '90', '180'], ['96', '98', '100', '196'], ['73', '66', '70', '142'], ['53', '46', '55', '101'], ['69', '74', '77', '149'], ['47', '56', '60', '115'], ['87', '79', '90', '175'], ['79', '70', '88', '164'], ['69', '70', '73', '141'], ['70', '65', '74', '141'], ['93', '95', '91', '184'], ['79', '80', '73', '152'], ['70', '73', '78', '148'], ['93', '89', '96', '192'], ['78', '75', '68', '147'], ['81', '90', '93', '183'], ['88', '92', '86', '177'], ['78', '83', '77', '159'], ['82', '86', '90', '177'], ['86', '82', '89', '175'], ['78', '83', '85', '175'], ['76', '83', '71', '149'], ['96', '93', '95', '192']]


In [ ]:
import numpy as np

data = np.loadtxt('test.csv' , delimiter=',' , skiprows = 1, dtype=float)
print(data)

[[ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [ ]:
print("total score 70 counts :",len(data[data==70]))
print("total score 80 counts :",len(data[data==80]))
print("total score 90 counts :",len(data[data==90]))

total score 70 counts : 5
total score 80 counts : 1
total score 90 counts : 4
