In [1]:
!ls -al

total 16
drwxr-xr-x 1 root root 4096 Mar  8 14:35 .
drwxr-xr-x 1 root root 4096 Mar 10 07:10 ..
drwxr-xr-x 4 root root 4096 Mar  8 14:34 .config
drwxr-xr-x 1 root root 4096 Mar  8 14:35 sample_data


In [3]:
print("hello world !")
for i in range(5):
  print(i)

hello world !
0
1
2
3
4


In [4]:
!python --version

Python 3.9.16


In [5]:
!pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
aeppl                         0.0.33
aesara                        2.7.9
alabaster                     0.7.13
albumentations                1.2.1
altair                        4.2.2
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.12.1
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atomicwrites                  1.4.1
attrs                         22.2.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.12.1
backcall                      0.2.0
backports.zoneinfo            0.2.1
beautifulsoup4                4.6.3
bleach                        6.0.0
blis                          0.7.9
bokeh                         2.4.3
branca                        0.6.0
bs4                           0.0.1
CacheC

In [1]:
!nvidia-smi
# GPU 연결 안 되어 있을 때 나옴.

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [1]:
!nvidia-smi
# GPU 사용량 알아볼 때 많이 쓰는 명령어 ! 알아두기 !!

Fri Mar 10 07:14:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Python Basic

In [1]:
# list
my_sent = ['Bravely','bold','Sir', 'Robin'] + [',','rode','from','Camelot']
words = my_sent[1:4]
print(words)
words.sort()
print(words)
words.append('bold')
print(words)
print(words.index('Sir'))
print(words[-1])
vocab = set(words)
print(vocab)
vocab_size = len(vocab)
print(vocab_size)
print('Sir' in words)

['bold', 'Sir', 'Robin']
['Robin', 'Sir', 'bold']
['Robin', 'Sir', 'bold', 'bold']
1
bold
{'Sir', 'bold', 'Robin'}
3
True


In [2]:
saying = ['After', 'all', 'is', 'said', 'and', 'done', 'all']
tokens = set(saying)
tokens = sorted(tokens)
print(tokens[2:5])

['and', 'done', 'is']


In [6]:
text = """문장 문장 문장 문장"""
print(text.split())

['문장', '문장', '문장', '문장']


In [6]:
list1 = [1, 2, 3]
print(type(list1))
print(list1[0], list1[-1]) #인덱스가 음수일 경우 리스트의 끝에서부터 셈 list1[1] = “str1”
print(list1) #리스트는 자료형이 다른 요소도 저장 가능
list2 = range(10)
print(list2)
print(type(list2)) #range Type출력
list2 = list(list2) #List Type으로 변환
print(type(list2))
print(list2[2:4]) # 인덱스 2에서 4(제외)까지 슬라이싱
print(list2[2:]) # 인덱스 2에서 끝까지 슬라이싱
print(list2[:2]) # 처음부터 인덱스 2(제외)까지 슬라이싱
print(list2[:]) # 전체 리스트 슬라이싱
print(list2[::2]) # 2씩 증가하면서 리스트 출력
print(list2[:-1]) # 슬라이싱 인덱스는 음수도 가능
list2[2:4] = [8, 9] # 슬라이스된 리스트에 새로운 리스트 할당
print(list2[2:4])
list2[2:5] = [8, 9] # ??
print(list2[2:5])

<class 'list'>
1 3
[1, 2, 3]
range(0, 10)
<class 'range'>
<class 'list'>
[2, 3]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[8, 9]
[8, 9, 5]


In [7]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

cat
dog
monkey
[0, 1, 4, 9, 16]


In [1]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'
for x in [-1, 0, 1]:
  print(sign(x))
# 출력 "negative", "zero", "positive", 한 줄에 하나씩 출력.

negative
zero
positive


In [2]:
def hello(name, loud=False):
  if loud:
    print ('HELLO, %s!' % name.upper())
  else:
    print ('Hello, %s' % name)

hello('Bob') # 출력 "Hello, Bob"
hello('Fred', loud=True) # 출력 "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


In [9]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
  print(x, y, z)
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
  print(x, y, z)

1 4 7
2 5 8
3 6 9
1 4 7
2 5 8
3 6 9


In [9]:
# Packing & Unpacking
# Packing
print(1) # print함수는 몇개의 인자를 받든지 상관하지 않음 print("a")
print("aa", "bb")
######################
def func(*args):
  print(args)
  print(type(args)) # Tuple

func(1, 2, 3, 'a')
######################

def func2(**kwargs):
  print(kwargs)
  print(type(kwargs)) # Dictionary
func2(a=1, b=2, c=3, d='a')

1
aa bb
(1, 2, 3, 'a')
<class 'tuple'>
{'a': 1, 'b': 2, 'c': 3, 'd': 'a'}
<class 'dict'>


In [12]:
# Unpacking
def printSum(a, b, c):
  total = a + b + c
  print(total)
  return

lst = [1, 2, 3]
# printSum(lst) #Error
printSum(*lst)

dic = {'a':1, 'b':2, 'c':3}

printSum(*dic) #key
printSum(**dic) #value

6
abc
6


In [12]:
# __call__
class HelloWorld():
  def __init__(self):
    pass
helloworld = HelloWorld()
# helloworld() #Error
class HelloWorld():
  def __init__(self):
    pass
  def __call__(self):
    print("Hello world")
helloworld = HelloWorld()
helloworld() # Hello world

Hello world


In [13]:
class Module():
  def __init__(self):
    #Initialize
    return
  def __call__(self, *input, **kwargs):
    ...
    result = self.forward(*input, **kwargs)
    return

In [15]:
import torch.nn as nn
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__() #use parant’s __init__ func.
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)

  def forward(self, x):
    # Max pooling over a (2, 2) window
    x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
    # If the size is a square you can only specify a single number
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    return x

net = Net()
print(net)
#net(inputData)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
)


# Numpy

In [11]:
import numpy as np
a = np.array([1, 2, 3]) # rank가 1인 배열 생성
print(type(a))
print(a.shape)
print(a.ndim)
print(a[0], a[1], a[2])
a[0]=5
print(a)
# 출력 "<type 'numpy.ndarray'>" # 출력 "(3,)"
# 출력 "1" # 출력 "1 2 3"
# 요소를 변경
# 출력 "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.ndim)
print(b[0, 0], b[0, 1], b[1, 0])
# rank가 2인 배열 생성 # 출력 "(2, 3)"
# 출력 "2"
# 출력 "1 2 4"

<class 'numpy.ndarray'>
(3,)
1
1 2 3
[5 2 3]
(2, 3)
2
1 2 4


In [12]:
import numpy as np
a = np.zeros((2,2)) # 모든 값이 0인 배열 생성 print(a) # 출력 "[[ 0. 0.]
# [0. 0.]]"
b = np.ones((1,2)) # 모든 값이 1인 배열 생성
print(b) # 출력 "[[ 1. 1.]]"
c = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성
print(c)
d = np.eye(2)
print(d)
# 출력 "[[ 7. 7.] # [ 7. 7.]]"
# 2x2 단위행렬 생성 # 출력 "[[ 1. 0.]
# [0. 1.]]"
e = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print(e) # 임의의 값 출력 "[[ 0.91940167 0.08143941]
#                  [ 0.68744134  0.87236687]]"

[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.14268792 0.37475622]
 [0.87472869 0.09331394]]


In [17]:
import numpy as np
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열 생성;
# b는 shape가 (2,2)인 배열이 됨: # [[2 3]
# [67]]
b = a[:2, 1:3]
print(a)
print(b)
# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됨.
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
# 출력 "2"
# b[0, 0]은 a[0, 1]과 같은 데이터
# 출력 "77"
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


In [17]:
import numpy as np
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.reshape(a, (2, 6))
print(b)
#b = a.reshape(2, 6) # Equivalent Function
# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조, 즉 슬라이싱된 배열을 수정하면 # 원본 배열 역시 수정됨.
print(b[0, 0])
b[0, 0] = 77
print(a[0, 0])
# 출력 "2"
# b[0, 0]은 a[0, 0]과 같은 데이터
# 출력 "77"

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
1
77


# Exercise
- Q1. Create a vector with values ranging from 10 to 49 (ex. 10, 11, ... 49)
- Q2. Create a vector with values ranging from 49 to 10 (ex. 49, 48, ... 10)
- Q3. Get the positions where elements of 'a' and 'b' match? (Hint: np.where) Input)
- Q4. Add 1 to matrix ‘a’ (Hint: Broadcast) 
- Q5. Swap rows 1 and 2 in the array 'a’ at Q4(HARD)
- Q6. Remove Negative values in the array ‘b’ (HARD, Hint: np.where)

In [20]:
# Q.1
print(np.arange(10,50))

# Q.2
print(np.arange(10,50,-1))
#print(np.arange(10,50)[::-1])

# Q.3
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))
#Output: => array([1, 3, 5, 7])

a = np.arange(9).reshape(3,3)
# Q.4
print(a+1)

# Q.5
print(a[[1,0,2],:])

# Q.6
a = np.array((3,-2,2,-1,3))
print(a[np.where(a>=0)])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[]
(array([1, 3, 5, 7]),)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[3 2 3]


# Tensor

numpy만으로는 GPU에 올릴 수 없다.

In [22]:
import torch
import numpy as np
t1 = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
t2 = torch.tensor(np.arange(7)) #Same
print(t1.shape, t2.shape)
print(t1.dim())
print(t1.shape)
print(t1.size())
print(t1[:2], t1[3:])

torch.Size([7]) torch.Size([7])
1
torch.Size([7])
torch.Size([7])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [28]:
# Broadcasting

import torch
import numpy as np
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
#m2 = torch.FloatTensor(3) # 3 -> Error
#m2 = torch.FloatTensor([3,0]) # 3 -> Error // 원래 의도한 바.
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [31]:
#Mul vs MatMul
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [32]:
import torch
import numpy as np
t = torch.FloatTensor([[1, 2], [3, 4]]) #torch.tensor is not work. Long Tensor...
print(t.type())
print(t)
print(t.mean()) # 모든 값에 대한 평균
print(t.mean(dim=0)) # Remove Dim 0 // 바깥의 차원에서 계산해줘.
print(t.mean(dim=1))
print(t.mean(dim=-1))

torch.FloatTensor
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [36]:
import torch
import numpy as np
t = np.arange(12).reshape(-1, 2, 3) # -1은 알아서서 들어감. // -1은 batch size, 2는 텍스트 길이,3은 임베딩 길이로 일반적으로 사용함.
print(t.shape)
floatT = torch.FloatTensor(t)
print(floatT.shape)
print(floatT)
print(floatT.view([-1, 3]))
print(floatT.view([-1, 4]))
print(floatT.shape)

(2, 2, 3)
torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.Size([2, 2, 3])


# Practice

In [25]:
import torch
t = np.arange(24)
print(t.shape)
floatT = torch.FloatTensor(t)
# print(floatT.view([-1, 2, 3]))
print(floatT.view([-1, 2, 3])[2:4,:,1])

(24,)
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.]]])
tensor([[13., 16.],
        [19., 22.]])


# Linear Regression

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [3], [4]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000

# x와 y를 만족하는 Weight와 bias를 찾아라. 러닝 레이트는 0.01로 해라.
# epochs는 1000번 해라.

# 중요한 것 : x,y(데이터) 와 optimizer ,model 어떻게 쓸 것인가.

In [31]:
for epoch in range(nb_epochs + 1): # H(x) 계산
  hypothesis = x_train * W + b
# cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)
# cost로 H(x) 개선
  optimizer.zero_grad() # optimizer를 0으로 초기화 시킨다.
  cost.backward()
  optimizer.step()
# 100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format( epoch, nb_epochs, W.item(), b.item(), cost.item()))

# 나의 모델은 hypothesis이고, 값을 넣은 값과 MSE를 구한다.
# Backpropagation 후 optimization한다.

Epoch    0/1000 W: 0.133, b: 0.060 Cost: 9.666667
Epoch  100/1000 W: 1.162, b: 0.632 Cost: 0.019523
Epoch  200/1000 W: 1.127, b: 0.711 Cost: 0.012064
Epoch  300/1000 W: 1.100, b: 0.773 Cost: 0.007455
Epoch  400/1000 W: 1.079, b: 0.821 Cost: 0.004607
Epoch  500/1000 W: 1.062, b: 0.859 Cost: 0.002847
Epoch  600/1000 W: 1.049, b: 0.890 Cost: 0.001759
Epoch  700/1000 W: 1.038, b: 0.913 Cost: 0.001087
Epoch  800/1000 W: 1.030, b: 0.932 Cost: 0.000672
Epoch  900/1000 W: 1.024, b: 0.946 Cost: 0.000415
Epoch 1000/1000 W: 1.019, b: 0.958 Cost: 0.000256


# Practice

In [32]:
x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# Train This values!!
# Tip: Learning rate should be less than 1e-5

# 내가 가지고있는 Data가, 3차원이 나오도록 학습을 해라.

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
x_train = torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5) # Learning rate should be small

In [34]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  # H(x) 계산
  hypothesis = x_train.matmul(W) + b # Not X * W!!
  # cost 계산
  # cost = torch.mean((hypothesis - y_train) ** 2)
  cost = F.mse_loss(hypothesis, y_train) # Torch는 다양한 Loss Function 지원
  # cost로 H(x) 개선
  optimizer.zero_grad() # 초기화
  cost.backward()
  optimizer.step()
  # 100번마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item())) # item() get one single value))

Epoch    0/1000 Cost: 29661.800781
Epoch  100/1000 Cost: 1.563628
Epoch  200/1000 Cost: 1.497595
Epoch  300/1000 Cost: 1.435044
Epoch  400/1000 Cost: 1.375726
Epoch  500/1000 Cost: 1.319507
Epoch  600/1000 Cost: 1.266222
Epoch  700/1000 Cost: 1.215703
Epoch  800/1000 Cost: 1.167810
Epoch  900/1000 Cost: 1.122429
Epoch 1000/1000 Cost: 1.079390


In [63]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
mu = x_train.mean(dim=0)
sigma = x_train.std(dim=0)
norm_x_train = (x_train - mu) / sigma
print(norm_x_train)

tensor([[-1.0674, -0.3758, -0.8398],
        [ 0.7418,  0.2778,  0.5863],
        [ 0.3799,  0.5229,  0.3486],
        [ 1.0132,  1.0948,  1.1409],
        [-1.0674, -1.5197, -1.2360]])


In [35]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [36]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
  def forward(self, x):
    return self.linear(x)

In [37]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) # 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [38]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  # H(x) 계산
  prediction = model(x_train)
  # cost 계산
  cost = F.mse_loss(prediction, y_train)
  # cost로 H(x) 개선 optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  # 20번마다 로그 출력
  print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/20 Cost: 44996.351562
Epoch    1/20 Cost: 14109.037109
Epoch    2/20 Cost: 729.464844
Epoch    3/20 Cost: 25821.099609
Epoch    4/20 Cost: 50069.687500
Epoch    5/20 Cost: 35481.867188
Epoch    6/20 Cost: 4914.197754
Epoch    7/20 Cost: 6260.877441
Epoch    8/20 Cost: 37411.843750
Epoch    9/20 Cost: 49558.894531
Epoch   10/20 Cost: 23669.646484
Epoch   11/20 Cost: 308.010193
Epoch   12/20 Cost: 16077.546875
Epoch   13/20 Cost: 46270.054688
Epoch   14/20 Cost: 43579.039062
Epoch   15/20 Cost: 12220.777344
Epoch   16/20 Cost: 1328.129639
Epoch   17/20 Cost: 27967.906250
Epoch   18/20 Cost: 50400.097656
Epoch   19/20 Cost: 33477.253906
Epoch   20/20 Cost: 3714.424316


In [40]:
# CNN 예시

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNN(nn.Module):
  def __init__(self):
    super(CNN, self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=5, stride=1)
    self.conv2 = nn.Conv2d(in_channels=3, out_channels=10, kernel_size=5, stride=1)
    self.fc1 = nn.Linear(10 * 12 * 12, 50)
    self.fc2 = nn.Linear(50,10)

  def forward(self, x):
    print("연산 전", x.size())
    x = F.relu(self.conv1(x))
    print("conv1 연산 후", x.size())
    x = F.relu(self.conv2(x))
    print("conv2 연산 후", x.size())
    x = x.view(-1, 10 * 12 * 12)
    print("차원 감소 후", x.size())
    x = F.relu(self.fc1(x))
    print("fc1 연산 후", x.size())
    x = F.relu(self.fc2(x))
    print("fc2 연산 후", x.size())
    return x
cnn = CNN()
output = cnn(torch.randn(10, 1, 20, 20)) # Input Size : (10, 1, 20, 20)
    

연산 전 torch.Size([10, 1, 20, 20])
conv1 연산 후 torch.Size([10, 3, 16, 16])
conv2 연산 후 torch.Size([10, 10, 12, 12])
차원 감소 후 torch.Size([10, 1440])
fc1 연산 후 torch.Size([10, 50])
fc2 연산 후 torch.Size([10, 10])


# GPU

In [39]:
import torch
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
#net = Model.to(device)
#inputs = data.to(device)

cuda


In [ ]:
#