# Q.1
아래 출력값을 갖도록 a 변수값을 설정 (Hint: np.arange(n) 활용)

In [3]:
#a = ??
import torch
import numpy as np

a = np.arange(24).reshape(2,3,4)

print("Shape :", a.shape)
print("Value :", a)

Shape : (2, 3, 4)
Value : [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



#Output
Shape : (2,3,4)
- Value : [[[ 0 1 2 3]
- [ 4 5 6 7]
- [8 9 10 11]

- [[12 13 14 15]
- [16 17 18 19]
*이탤릭체 텍스트*- [20 21 22 23]]]

# Q.2
Exercise 1의 a값과 slicing을 통해, 다음 두 값을 출력

In [14]:
#print(a[???]) #Problem1
#print(a[???]) #Problem2

print(a[0,1:3,2:4]) #Problem1
print(a[0:1,1:3,2:4]) #Problem2 # 0:1을 사용해서 shape을 유지할 수 있다.
# print(np.reshape(a[0,1:3,2:4], (1,2,2))) #Problem2

[[ 6  7]
 [10 11]]
[[[ 6  7]
  [10 11]]]


# Q.3
test.csv 데이터를 활용하여, 70, 80, 90에 대한 Total Score 구하기 (nn.Module 활용) *Hint: numpy genfromtext 활용

In [5]:
data = open('test.csv', 'r')
print(data)

<_io.TextIOWrapper name='test.csv' mode='r' encoding='UTF-8'>


In [6]:
import csv

with open('test.csv' , 'r') as f :
    dat = [k for k in csv.reader(f)]
print(dat)

[['73', '80', '75', '152'], ['93', '88', '93', '185'], ['89', '91', '90', '180'], ['96', '98', '100', '196'], ['73', '66', '70', '142'], ['53', '46', '55', '101'], ['69', '74', '77', '149'], ['47', '56', '60', '115'], ['87', '79', '90', '175'], ['79', '70', '88', '164'], ['69', '70', '73', '141'], ['70', '65', '74', '141'], ['93', '95', '91', '184'], ['79', '80', '73', '152'], ['70', '73', '78', '148'], ['93', '89', '96', '192'], ['78', '75', '68', '147'], ['81', '90', '93', '183'], ['88', '92', '86', '177'], ['78', '83', '77', '159'], ['82', '86', '90', '177'], ['86', '82', '89', '175'], ['78', '83', '85', '175'], ['76', '83', '71', '149'], ['96', '93', '95', '192']]


In [7]:
import numpy as np

data = np.loadtxt('test.csv' , delimiter=',' , skiprows = 1, dtype=float)
print(data)

[[ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [11]:
import numpy as np

data = np.genfromtxt('test.csv' , skip_header = 1 , delimiter = ',' , dtype = float)
# data = np.loadtxt('test.csv' , delimiter=',' , skiprows = 1, dtype=float)
print(data)
print("-----")
print(data[0])


[[ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]
-----
[ 93.  88.  93. 185.]


In [9]:
print("total score 70 counts :",len(data[data==70]))
print("total score 80 counts :",len(data[data==80]))
print("total score 90 counts :",len(data[data==90]))

total score 70 counts : 5
total score 80 counts : 1
total score 90 counts : 4


In [12]:
print("total score 70 up counts :",len(data[data>=70]))
print("total score 80 up counts :",len(data[data>=80]))
print("total score 90 up counts :",len(data[data>=90]))

total score 70 up counts : 85
total score 80 up counts : 62
total score 90 up counts : 44


In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from numpy import genfromtxt

# 크게 3단계. 데이터 load, 모델, 학습

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):    # 모델이 어떻게 생겼는지. 초기화.
        super().__init__()   
        self.linear = nn.Linear(3, 1) # 입력 3개에 output 1개
    def forward(self, x):
        return self.linear(x)

# data를 읽는 부분
my_data = genfromtxt('test.csv', delimiter=',')
x_train = torch.FloatTensor(my_data[:, :-1])
y_train = torch.FloatTensor(my_data[:, -1:]) # -1만하면 차원이 유지되지 않는다.
x_test = torch.FloatTensor([70, 80, 90])

print(x_train)
print(y_train)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.],
        [101.],
        [149.],
        [115.],
        [175.],
        [164.],
        [141.],
        [141.],
        [184.],
        [152.],
        [148.],
        [192.],
        [147.],
        [183.],
        [17

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from numpy import genfromtxt

# 크게 3단계. 데이터 load, 모델, 학습

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):    # 모델이 어떻게 생겼는지. 초기화.
        super().__init__()   
        self.linear = nn.Linear(3, 1) # 입력 3개에 output 1개 W1x1 + W2x2 + W3x3= y
    def forward(self, x):    
        return self.linear(x)

# data를 읽는 부분
my_data = genfromtxt('test.csv', delimiter=',')
x_train = torch.FloatTensor(my_data[:, :-1])
y_train = torch.FloatTensor(my_data[:, -1:]) # -1만하면 차원이 유지되지 않는다.
x_test = torch.FloatTensor([70, 80, 90])

# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 500
for epoch in range(nb_epochs + 1):
    # H(x) 계산
    prediction = model(x_train) # 자동으로 forward func. 실행됨. 모델이 예측한 값.
    # cost 계산
    cost = F.mse_loss(prediction, y_train) # 예측값, 실제값 차이 최소가 무엇인가.
    # cost로 H(x) 개선
    optimizer.zero_grad() # gradient descent 초기화
    cost.backward()       # MSE를 gradient descent로 backward를 해라.
    optimizer.step()      # 여기까지 하면 학습. 이렇게는 세트로 나옴.
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()		#list(model.parameters())[0].data[0][0]
    ))
print("Answer : ", model(x_test).data[0]) # x_test 값 70 80 90을 넣었을 때 값이 무엇인가.

Epoch    0/500 Cost: 11901.990234
Epoch    1/500 Cost: 4408.408691
Epoch    2/500 Cost: 1637.820190
Epoch    3/500 Cost: 613.453735
Epoch    4/500 Cost: 234.713196
Epoch    5/500 Cost: 94.679016
Epoch    6/500 Cost: 42.900879
Epoch    7/500 Cost: 23.753635
Epoch    8/500 Cost: 16.670870
Epoch    9/500 Cost: 14.048639
Epoch   10/500 Cost: 13.075683
Epoch   11/500 Cost: 12.712432
Epoch   12/500 Cost: 12.574636
Epoch   13/500 Cost: 12.520206
Epoch   14/500 Cost: 12.496600
Epoch   15/500 Cost: 12.484413
Epoch   16/500 Cost: 12.476398
Epoch   17/500 Cost: 12.470000
Epoch   18/500 Cost: 12.464163
Epoch   19/500 Cost: 12.458505
Epoch   20/500 Cost: 12.452994
Epoch   21/500 Cost: 12.447483
Epoch   22/500 Cost: 12.441991
Epoch   23/500 Cost: 12.436484
Epoch   24/500 Cost: 12.431036
Epoch   25/500 Cost: 12.425545
Epoch   26/500 Cost: 12.420096
Epoch   27/500 Cost: 12.414623
Epoch   28/500 Cost: 12.409159
Epoch   29/500 Cost: 12.403717
Epoch   30/500 Cost: 12.398276
Epoch   31/500 Cost: 12.392819